#!/usr/bin/env python3
from __future__ import annotations

import argparse
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
SRC_ROOT = REPO_ROOT / "src"
if str(SRC_ROOT) not in sys.path:
    sys.path.insert(0, str(SRC_ROOT))

from dinoml.kernels.providers.cutlass.gemm import (  # noqa: E402
    cutlass_gemm_candidate_set,
    cutlass_gemm_candidates,
    render_cutlass_gemm_source,
)

DEFAULT_CHUNK_SIZE = 16


def cutlass_gemm_unit_plan(op: str, dtype: str, candidates: list[dict] | None = None) -> dict:
    target = {"name": "cuda", "arch": "sm_80"}
    candidate_set = cutlass_gemm_candidate_set(op, dtype, target=target)
    selected_candidates = (
        [dict(candidate) for candidate in candidates]
        if candidates is not None
        else [dict(candidate) for candidate in cutlass_gemm_candidates(op, dtype, target=target)]
    )
    return {
        "entries": [
            {
                "op": op,
                "dtype": dtype,
                "candidate_set": candidate_set,
                "candidate_set_id": candidate_set["candidate_set_id"],
                "candidate_set_key": candidate_set["candidate_set_key"],
                "candidates": selected_candidates,
                "kernel_symbols": sorted({str(candidate["kernel_symbol"]) for candidate in selected_candidates}),
                "profiler_symbols": sorted({str(candidate["profiler_symbol"]) for candidate in selected_candidates}),
            }
        ],
        "candidates": selected_candidates,
        "kernel_symbols": sorted({str(candidate["kernel_symbol"]) for candidate in selected_candidates}),
        "profiler_symbols": sorted({str(candidate["profiler_symbol"]) for candidate in selected_candidates}),
    }


def cutlass_gemm_unit_chunks(op: str, dtype: str, chunk_size: int) -> list[list[dict]]:
    if chunk_size <= 0:
        raise ValueError(f"chunk_size must be positive, got {chunk_size}")
    target = {"name": "cuda", "arch": "sm_80"}
    candidates = [dict(candidate) for candidate in cutlass_gemm_candidates(op, dtype, target=target)]
    if not candidates:
        raise ValueError(f"CUTLASS GEMM has no candidates for {op}/{dtype}")
    return [candidates[index : index + chunk_size] for index in range(0, len(candidates), chunk_size)]


def cutlass_gemm_chunk_filename(op: str, dtype: str, chunk_index: int) -> str:
    return f"{op}_{dtype}_{chunk_index:03d}.cu"


def cutlass_gemm_chunk_filenames(op: str, dtype: str, chunk_size: int) -> list[str]:
    return [
        cutlass_gemm_chunk_filename(op, dtype, chunk_index)
        for chunk_index, _ in enumerate(cutlass_gemm_unit_chunks(op, dtype, chunk_size))
    ]


def render_cutlass_gemm_unit(op: str, dtype: str, source: Path, candidates: list[dict] | None = None) -> str:
    return render_cutlass_gemm_source(source.read_text(encoding="utf-8"), cutlass_gemm_unit_plan(op, dtype, candidates))


def render_cutlass_gemm_chunk(op: str, dtype: str, source: Path, chunk_size: int, chunk_index: int) -> str:
    chunks = cutlass_gemm_unit_chunks(op, dtype, chunk_size)
    try:
        candidates = chunks[chunk_index]
    except IndexError as exc:
        raise ValueError(f"chunk_index {chunk_index} is out of range for {op}/{dtype}") from exc
    return render_cutlass_gemm_unit(op, dtype, source, candidates)


def write_cutlass_gemm_chunks(op: str, dtype: str, source: Path, output_dir: Path, chunk_size: int) -> None:
    chunks = cutlass_gemm_unit_chunks(op, dtype, chunk_size)
    output_dir.mkdir(parents=True, exist_ok=True)
    for stale_path in output_dir.glob(f"{op}_{dtype}_*.cu"):
        stale_path.unlink()
    for chunk_index, candidates in enumerate(chunks):
        output_path = output_dir / cutlass_gemm_chunk_filename(op, dtype, chunk_index)
        output_path.write_text(render_cutlass_gemm_unit(op, dtype, source, candidates), encoding="utf-8")


def write_cmake_chunk_manifest(output: Path, ops: list[str], dtypes: list[str], chunk_size: int) -> None:
    lines = ["# Generated by tools/generate_cutlass_gemm_unit.py", ""]
    for op in ops:
        for dtype in dtypes:
            lines.append(f"set(DINOML_CUTLASS_GEMM_CHUNKS_{op}_{dtype}")
            for filename in cutlass_gemm_chunk_filenames(op, dtype, chunk_size):
                lines.append(f'  "{filename}"')
            lines.append(")")
            lines.append("")
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines), encoding="utf-8")


def require_op_dtype(args: argparse.Namespace) -> tuple[str, str]:
    if args.op is None or args.dtype is None:
        raise SystemExit("--op and --dtype are required for this mode")
    return args.op, args.dtype


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--op")
    parser.add_argument("--dtype")
    parser.add_argument("--ops", nargs="+")
    parser.add_argument("--dtypes", nargs="+")
    parser.add_argument("--source", type=Path)
    parser.add_argument("--output", type=Path)
    parser.add_argument("--output-dir", type=Path)
    parser.add_argument("--chunk-size", type=int, default=DEFAULT_CHUNK_SIZE)
    parser.add_argument("--chunk-index", type=int)
    parser.add_argument("--list-chunks", action="store_true")
    parser.add_argument("--write-cmake-chunk-manifest", type=Path)
    args = parser.parse_args()

    if args.write_cmake_chunk_manifest is not None:
        if not args.ops or not args.dtypes:
            raise SystemExit("--ops and --dtypes are required with --write-cmake-chunk-manifest")
        write_cmake_chunk_manifest(args.write_cmake_chunk_manifest, args.ops, args.dtypes, args.chunk_size)
        return

    op, dtype = require_op_dtype(args)

    if args.list_chunks:
        print("\n".join(cutlass_gemm_chunk_filenames(op, dtype, args.chunk_size)))
        return

    if args.source is None:
        raise SystemExit("--source is required unless --list-chunks is used")

    if args.output_dir is not None:
        write_cutlass_gemm_chunks(op, dtype, args.source, args.output_dir, args.chunk_size)
        return

    if args.output is None:
        raise SystemExit("--output or --output-dir is required")

    rendered = (
        render_cutlass_gemm_chunk(op, dtype, args.source, args.chunk_size, args.chunk_index)
        if args.chunk_index is not None
        else render_cutlass_gemm_unit(op, dtype, args.source)
    )
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(rendered, encoding="utf-8")


if __name__ == "__main__":
    main()
